/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controlador.PacienteCrud;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class TelaAtualizar extends javax.swing.JFrame {

    private final PacienteCrud Controlador;
    private ConsultarPaciente view;

    /**
     * Creates new form TelaAtualizar
     */
    public TelaAtualizar() {
        initComponents();
        Controlador=new Controlador.PacienteCrud(view);
        
        txtObs.setVisible(false);
        txttelefone.setVisible(false);
        txtNome.setVisible(false);
        txtcpf.setVisible(false);
        lblCPF1.setVisible(false);
        lblTelegone1.setVisible(false);
        lblNome1.setVisible(false);
        lblObs1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNome = new javax.swing.JCheckBox();
        cbTelefone = new javax.swing.JCheckBox();
        cbObs = new javax.swing.JCheckBox();
        cbPF = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtNomeAntes = new javax.swing.JTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        txttelefone = new javax.swing.JFormattedTextField();
        btnMenu = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblTelegone1 = new javax.swing.JLabel();
        lblObs1 = new javax.swing.JLabel();
        lblCPF1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cbNome.setForeground(new java.awt.Color(255, 255, 255));
        cbNome.setText("Nome");
        cbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeActionPerformed(evt);
            }
        });
        getContentPane().add(cbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 30));

        cbTelefone.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cbTelefone.setForeground(new java.awt.Color(255, 255, 255));
        cbTelefone.setText("Telefone");
        cbTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(cbTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 30));

        cbObs.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cbObs.setForeground(new java.awt.Color(255, 255, 255));
        cbObs.setText("Observacao");
        cbObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbObsActionPerformed(evt);
            }
        });
        getContentPane().add(cbObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 30));

        cbPF.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cbPF.setForeground(new java.awt.Color(255, 255, 255));
        cbPF.setText("CPF");
        cbPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPFActionPerformed(evt);
            }
        });
        getContentPane().add(cbPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 30));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("ID");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, -1));
        getContentPane().add(txtNomeAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, -1));

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, -1));

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view/tooth.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 100, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view/tooth_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 30, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alterar Dados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lblNome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(255, 255, 255));
        lblNome1.setText("Nome novo ");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblTelegone1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelegone1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelegone1.setText("Telefone novo");
        getContentPane().add(lblTelegone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblObs1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblObs1.setForeground(new java.awt.Color(255, 255, 255));
        lblObs1.setText("Observacao novo");
        getContentPane().add(lblObs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblCPF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF1.setText("CPF novo");
        getContentPane().add(lblCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGround/view/fundoAzul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeActionPerformed
        if(cbNome.isSelected()){
            lblNome.setVisible(true);
            txtNome.setVisible(true);
            lblNome1.setVisible(true);
            
        }else{
            txtNome.setVisible(false);
            lblNome1.setVisible(false);
            }
            
    }//GEN-LAST:event_cbNomeActionPerformed

    private void cbTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTelefoneActionPerformed
        if(cbTelefone.isSelected()){
          txttelefone.setVisible(true);
          lblTelegone1.setVisible(true);
        }else
        {
          txttelefone.setVisible(false);
          lblTelegone1.setVisible(false);
        }
    }//GEN-LAST:event_cbTelefoneActionPerformed

    private void cbObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbObsActionPerformed
      if(cbObs.isSelected()){
        txtObs.setVisible(true);
        lblObs1.setVisible(true);
        }else{
            txtObs.setVisible(false);
            lblObs1.setVisible(false);
            }
    }//GEN-LAST:event_cbObsActionPerformed

    private void cbPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPFActionPerformed
        if(cbPF.isSelected())
        {
        txtcpf.setVisible(true);
        lblCPF1.setVisible(true);
        }else{
            txtcpf.setVisible(false);
            lblCPF1.setVisible(false);
            }
    }//GEN-LAST:event_cbPFActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
           if(cbNome.isSelected()){
            String Id=getTxtNomeAntes().getText();
            int id=Integer.parseInt(Id);
            String Nome=getTxtNome().getText();
            String nomeAlterado=new Controlador.PacienteCrud(view).AlterarPaciente("UPDATE paciente SET nome = ? WHERE IdPaciente = ?;", Nome,id);
           }
           if(cbPF.isSelected())
           {
            String Id=getTxtNomeAntes().getText();
            int id=Integer.parseInt(Id);
            String CPF=getTxtcpf().getText();
            String nomeAlterado=new Controlador.PacienteCrud(view).AlterarPaciente("UPDATE paciente SET CPF = ? WHERE IdPaciente = ?;", CPF,id);
           }
           if(cbTelefone.isSelected())
           {
            String Id=getTxtNomeAntes().getText();
            int id=Integer.parseInt(Id);
            String telefone=getTxttelefone().getText();
            String nomeAlterado=new Controlador.PacienteCrud(view).AlterarPaciente("UPDATE paciente SET telefoneContato = ? WHERE IdPaciente = ?;", telefone,id);
           }
           if(cbObs.isSelected())
           {
            String Id=getTxtNomeAntes().getText();
            int id=Integer.parseInt(Id);
            String observacoes=getTxtObs().getText();
            String nomeAlterado=new Controlador.PacienteCrud(view).AlterarPaciente("UPDATE paciente SET observacoes = ? WHERE IdPaciente = ?;", observacoes,id);
           }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        TelaCrudsPacienteAcoes cruds=new TelaCrudsPacienteAcoes();
        cruds.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ConsultarPaciente consulta=new ConsultarPaciente();
       consulta.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JCheckBox cbNome;
    private javax.swing.JCheckBox cbObs;
    private javax.swing.JCheckBox cbPF;
    private javax.swing.JCheckBox cbTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblObs1;
    private javax.swing.JLabel lblTelegone1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeAntes;
    private javax.swing.JTextField txtObs;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtObs() {
        return txtObs;
    }

    public void setTxtObs(JTextField txtObs) {
        this.txtObs = txtObs;
    }

    public JTextField getTxtTelefone() {
        return txttelefone;
    }

    public JTextField getTxtNomeAntes() {
        return txtNomeAntes;
    }

    public void setTxtNomeAntes(JTextField txtNomeAntes) {
        this.txtNomeAntes = txtNomeAntes;
    }

    public JFormattedTextField getTxtcpf() {
        return txtcpf;
    }

    public void setTxtcpf(JFormattedTextField txtcpf) {
        this.txtcpf = txtcpf;
    }

    public JFormattedTextField getTxttelefone() {
        return txttelefone;
    }

    public void setTxttelefone(JFormattedTextField txttelefone) {
        this.txttelefone = txttelefone;
    }

    
    
    
    
   }


